name: Build

on:
 push:
   tags:
     - '*'
 workflow_dispatch:
   branches:
     - main
  
  
jobs:
  build:
    name: Build - ${{ matrix.targetPlatform }} - Unity ver. ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    environment: Unity build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.10f1
        targetPlatform:
          - StandaloneLinux64
          #- StandaloneWindows64
          - StandaloneWindows
          - StandaloneOSX
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      #  # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v2
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     projectPath: .
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Zip build
        run: |
          pushd build/${{ matrix.targetPlatform }}
          zip -r ../../${{ matrix.targetPlatform }}.zip .
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.targetPlatform }}.zip
          name: Release ${{ github.ref }}